### PR TITLE
Fix #74, #75: Implement {Int,Long}#{not}, {Int, Long, Float, Double}#{unaryPlus,unaryMinus}, Boolean#not

### LINKED ISSUE #74: 1.not(): thread 'main' panicked at 'unknown intrinsic IntNot'
I assume this should be the same as `!1` (which works)?

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
This is duplicating things a bit with `emit_un`, but I couldn't make calling that function instead work:

```
                Intrinsic::IntNeg => {
                    let opnd = e.object.as_ref().unwrap().clone();
                    let unOp = ExprUnType { id: e.id, pos: e.pos, op: UnOp::Neg, opnd };
                    self.emit_un(&unOp, dest)
                },
                Intrinsic::IntNot => {
                    let opnd = e.object.as_ref().unwrap().clone();
                    let unOp = ExprUnType { id: e.id, pos: e.pos, op: UnOp::Not, opnd };
                    self.emit_un(&unOp, dest)
                },
```

doesn't work due to:

```
error[E0597]: `unOp` does not live long enough
    --> src/baseline/expr.rs:1046:34
     |
94   | impl<'a, 'b, 'ast> ExprGen<'a, 'b, 'ast>
     |              ---- lifetime `'ast` defined here
...
1046 |                     self.emit_un(&unOp, dest)
     |                     -------------^^^^^-------
     |                     |            |
     |                     |            borrowed value does not live long enough
     |                     argument requires that `unOp` is borrowed for `'ast`
1047 |                 },
     |                 - `unOp` dropped here while still borrowed
```

Let me know which way you prefer!

File: src/baseline/expr.rs [hunk 1]
```diff
@@ -1392,13 +1396,49 @@ where
...
 
         self.emit_intrinsic_bin(lhs, rhs, dest, intr, None);
     }
 
+    fn emit_intrinsic_unary(
+        &mut self,
+        lhs: &'ast Expr,
+        dest: ExprStore,
+        intr: Intrinsic,
+        op: Option<BinOp>,
```
Comment (dinfuehr) [inline src/baseline/expr.rs]: `op` isn't used here, also pretty sure the type is wrong. For unary operators it should be `UnOp`.

File: src/baseline/expr.rs [hunk 2]
```diff
@@ -1029,7 +1029,7 @@ where
                 Intrinsic::ByteNot => self.emit_intrinsic_bin_call(e, dest, intrinsic),
 
                 Intrinsic::BoolEq => self.emit_intrinsic_bin_call(e, dest, intrinsic),
-                Intrinsic::BoolNot => self.emit_intrinsic_bin_call(e, dest, intrinsic),
+                Intrinsic::BoolNot => self.emit_intrinsic_unary_call(e, dest, intrinsic),
```
Comment (dinfuehr) [inline src/baseline/expr.rs]: I think it's better to have a separate function for unary intrinsics.

File: src/baseline/expr.rs (hunk 1 above)
Comment (soc) [reply src/baseline/expr.rs]: Will do!

File: src/baseline/expr.rs (hunk 2 above)
Comment (soc) [reply src/baseline/expr.rs]: Will do!

**Comment by soc** [comment]
@dinfuehr Does this look good?

File: src/baseline/ast/expr.rs [hunk 3]
```diff
@@ -1443,10 +1467,12 @@ where
             Intrinsic::IntMul => self.asm.int_mul(MachineMode::Int32, dest, lhs, rhs),
             Intrinsic::IntDiv => self.asm.int_div(MachineMode::Int32, dest, lhs, rhs),
             Intrinsic::IntMod => self.asm.int_mod(MachineMode::Int32, dest, lhs, rhs),
+            Intrinsic::IntNeg => self.asm.int_neg(MachineMode::Int32, dest, lhs),
```
Comment (dinfuehr) [inline src/baseline/ast/expr.rs]: Can you please move these unary intrinsics out of `emit_intrinsic_bin`? `lhs`, `rhs` and `BinOp` doesn't make sense for them.

File: src/baseline/ast/expr.rs [hunk 4]
```diff
@@ -992,10 +1006,13 @@ where
                 Intrinsic::IntMul => self.emit_intrinsic_bin_call(e, dest, intrinsic),
                 Intrinsic::IntDiv => self.emit_intrinsic_bin_call(e, dest, intrinsic),
                 Intrinsic::IntMod => self.emit_intrinsic_bin_call(e, dest, intrinsic),
+                Intrinsic::IntNeg => self.emit_intrinsic_unary_call(e, dest, intrinsic),
+                Intrinsic::IntPlus => self.emit_expr(e.object.as_ref().unwrap(), dest),
```
Comment (dinfuehr) [inline src/baseline/ast/expr.rs]: Could you please also invoke `emit_intrinsic_unary_call` here as well instead of handling the new intrinsics directly? Then we only have one implementation for them and the code should be more in line with the other intrinsics.

No need to change existing code - just the new intrinsics.

File: src/baseline/ast/expr.rs (hunk 3 above)
Comment (soc) [reply src/baseline/ast/expr.rs]: Agreed, will do. :-)

File: src/baseline/ast/expr.rs (hunk 4 above)
Comment (soc) [reply src/baseline/ast/expr.rs]: Ok, will do!

File: src/baseline/ast/expr.rs (hunk 3 above)
Comment (soc) [reply src/baseline/ast/expr.rs]: Also did the same for BoolNot.

**Comment by soc** [comment]
Pushed!

**Comment by dinfuehr** [comment]
Very cool, thanks!
